export const stateData = {
  AL: { name: "Alabama", minBenefit: 45, maxBenefit: 275 },
  AK: { name: "Alaska", minBenefit: 56, maxBenefit: 370 },
  AZ: { name: "Arizona", minBenefit: 50, maxBenefit: 240 },
  AR: { name: "Arkansas", minBenefit: 81, maxBenefit: 451 },
  CA: { name: "California", minBenefit: 40, maxBenefit: 450 },
  CO: { name: "Colorado", minBenefit: 25, maxBenefit: 636 },
  CT: { name: "Connecticut", minBenefit: 15, maxBenefit: 685 },
  DE: { name: "Delaware", minBenefit: 20, maxBenefit: 400 },
  DC: { name: "District of Columbia", minBenefit: 50, maxBenefit: 444 },
  FL: { name: "Florida", minBenefit: 32, maxBenefit: 275 },
  GA: { name: "Georgia", minBenefit: 55, maxBenefit: 365 },
  HI: { name: "Hawaii", minBenefit: 5, maxBenefit: 695 },
  ID: { name: "Idaho", minBenefit: 72, maxBenefit: 499 },
  IL: { name: "Illinois", minBenefit: 51, maxBenefit: 542 },
  IN: { name: "Indiana", minBenefit: 37, maxBenefit: 390 },
  IA: { name: "Iowa", minBenefit: 73, maxBenefit: 531 },
  KS: { name: "Kansas", minBenefit: 135, maxBenefit: 540 },
  KY: { name: "Kentucky", minBenefit: 39, maxBenefit: 569 },
  LA: { name: "Louisiana", minBenefit: 10, maxBenefit: 275 },
  ME: { name: "Maine", minBenefit: 89, maxBenefit: 511 },
  MD: { name: "Maryland", minBenefit: 50, maxBenefit: 487 },
  MA: { name: "Massachusetts", minBenefit: 55, maxBenefit: 974 },
  MI: { name: "Michigan", minBenefit: 157, maxBenefit: 362 },
  MN: { name: "Minnesota", minBenefit: 31, maxBenefit: 890 },
  MS: { name: "Mississippi", minBenefit: 30, maxBenefit: 235 },
  MO: { name: "Missouri", minBenefit: 35, maxBenefit: 320 },
  MT: { name: "Montana", minBenefit: 183, maxBenefit: 618 },
  NE: { name: "Nebraska", minBenefit: 70, maxBenefit: 490 },
  NV: { name: "Nevada", minBenefit: 16, maxBenefit: 533 },
  NH: { name: "New Hampshire", minBenefit: 32, maxBenefit: 427 },
  NJ: { name: "New Jersey", minBenefit: 144, maxBenefit: 804 },
  NM: { name: "New Mexico", minBenefit: 96, maxBenefit: 514 },
  NY: { name: "New York", minBenefit: 116, maxBenefit: 504 },
  NC: { name: "North Carolina", minBenefit: 15, maxBenefit: 350 },
  ND: { name: "North Dakota", minBenefit: 43, maxBenefit: 657 },
  OH: { name: "Ohio", minBenefit: 149, maxBenefit: 530 },
  OK: { name: "Oklahoma", minBenefit: 16, maxBenefit: 476 },
  OR: { name: "Oregon", minBenefit: 171, maxBenefit: 733 },
  PA: { name: "Pennsylvania", minBenefit: 68, maxBenefit: 594 },
  RI: { name: "Rhode Island", minBenefit: 62, maxBenefit: 661 },
  SC: { name: "South Carolina", minBenefit: 42, maxBenefit: 326 },
  SD: { name: "South Dakota", minBenefit: 28, maxBenefit: 466 },
  TN: { name: "Tennessee", minBenefit: 30, maxBenefit: 275 },
  TX: { name: "Texas", minBenefit: 70, maxBenefit: 549 },
  UT: { name: "Utah", minBenefit: 38, maxBenefit: 661 },
  VT: { name: "Vermont", minBenefit: 75, maxBenefit: 583 },
  VA: { name: "Virginia", minBenefit: 60, maxBenefit: 378 },
  WA: { name: "Washington", minBenefit: 295, maxBenefit: 929 },
  WV: { name: "West Virginia", minBenefit: 24, maxBenefit: 424 },
  WI: { name: "Wisconsin", minBenefit: 54, maxBenefit: 370 },
  WY: { name: "Wyoming", minBenefit: 38, maxBenefit: 533 },
};
